version: '3.8'

services:
  ctfbackend:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16.1-alpine3.19
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres:
